version: '2'
services:
  medmanagerdb:
    image: medmanagerdb
    container_name: medmanagerdb
    build:
      context: ./medmanagerdb
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    ports:
      - 3306:3306
    volumes:
      - /home/${USER}/medmanager:/var/lib/mysql
      - /home/${USER}/docker/medmanagerdb:/home/scripts